brew 'fzf'
brew 'gh'
brew 'kubectl'
brew 'neovim'
brew 'node' # Needed for CoC
brew 'pyenv'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tmux'
brew 'zplug'
brew '1password-cli'

cask 'alfred'
cask 'git-credential-manager-core'
cask 'iterm2'
cask 'obsidian'
cask 'rectangle'
cask 'rocket'
cask 'spotify'
cask 'todoist'
