if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  exit
fi

# Enable Powerlevel10k instant prompt. Must be near the top, before any output.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load ~/.zsh_plugins.txt

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# Set programming directory
if [ -f ~/.work ]; then
  DEV_HOME="/Users/mshelley/Development"
else 
  DEV_HOME="/Users/mackenzie/programming"
fi

# Square stuff (first so my stuff overrides)
if [ -f ~/.work ]; then
  source "$DEV_HOME/dotfiles/config_files/square/zshrc"
fi
source "$DEV_HOME/dotfiles/config/zsh/git_functions.sh"
source "$DEV_HOME/dotfiles/config/zsh/py_env_functions.sh"

# Setup Goose stuff
source "$DEV_HOME/dotfiles/config/zsh/goose.sh"

# Put homebrew ahead of system on path PATH=/user/local/bin:$PATH
# General
export VISUAL='nvim'
export EDITOR=$VISUAL
export TERM=xterm-256color

## History
# This gets set in square zshrc :/ unsetopt appendhistory
setopt inc_append_history
setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

## make reverse search work in vim mode
bindkey '^R' history-incremental-pattern-search-backward

# Put poetry on path
PATH=$PATH:~/.poetry/bin

# Setup poetry autocomplete
fpath+=~/.zfunc


pr_warning() {
  local pr_warning_string='Did you:\n * Make everything final that should be final\n * Check for random new lines\n * Actually test this as much as possible\n * SQUASH\n * CHECK FOR WARNINGS. NPES.\n * If it involves $$, fucking be careful.'
  echo $pr_warning_string
}


# Aliases
alias gpr='gh pr create --web' 
alias vi='nvim'
alias gl='git log'
alias gb='git branch -vv'
alias gco='git checkout'
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gppr='pr_warning && git push origin HEAD:$(git branch | grep \* | cut -c3-) && gpr'
alias gfppr='pr_warning && git push -f origin HEAD:$(git branch | grep \* | cut -c3-) && gpr'
alias gfp='pr_warning && git push -f origin HEAD:$(git branch | grep \* | cut -c3-)'
alias gp='pr_warning && git push origin HEAD:$(git branch | grep \* | cut -c3-)'
alias gbd='delete_merged_branches'
alias gupdate='gco $(get_main_branch) && git pull && gco - && git rebase $(get_main_branch)'
alias gc='gco $(get_main_branch) && git pull && gbd'
alias ku='kubectl'
alias gra='git commit -a --fixup head && git rebase -i --autosquash head~2'
alias grap='gra && gfp'
alias sourcez='source ~/.zshrc'
alias editz="nv $DEV_HOME/dotfiles/config/zsh/zshrc"
alias grafp='gra && gfp'
alias tap='touch'
alias pssh='ssh pi@192.168.1.69'
alias nv='nvim'
alias branch='git branch --show-current | tr -d "\n"'
alias y='yazi'
alias ..='cd ..'
alias ...='cd ../..'

zshaddhistory() {
  [[ $1 =~ '^(ls|cd|gs|gd|gl|gb|pwd|exit|y)\s*$' ]] && return 1
  return 0
}

gcob() {
  zparseopts -E -A args -- t: j:
  target=$args[-t]
  jira=$args[-j]

  if [ -z $target ]; then
    target=$(get_main_branch)
  fi

  if [ -z $jira ]; then
    gco --track -b mshelley."$1" $target
    return
  fi

  gco --track -b mshelley."$jira"."$1" $target
}

gcomb() {
  zparseopts -E -A args -- t: j:
  target=$args[-t]
  jira=$args[-j]

  if [ -z $target ]; then
    target=$(get_main_branch)
  fi

  if [ -z $jira ]; then
    gco $(get_main_branch) && gco --track -b mshelley."$1" $target
    return
  fi

  gco $(get_main_branch) && gco --track -b mshelley."$jira"."$1" $target
}

gcom() {
  gco mshelley."$1"
}

ftmf() {
  ulimit -n 4096
}

drmi() {
  docker rmi -f $(docker images -q)
}


find_big_dirs() {
  du -k -h -d1 * | sort -h
}

# Fix too many files issue
ftmf

source ~/.p10k.zsh
base16_material

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(fnm env --use-on-cd --shell zsh)"

# Completion setup
# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]} r:|[._-]=** r:|=**' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' max-errors 4 numeric
zstyle ':completion:*' substitute 1
zstyle :compinstall filename '/Users/mackenzie/.zshrc'

# enables cding without specifying full root path
setopt autocd

autoload -Uz compinit
zmodload -i zsh/complist
compinit
# End of lines added by compinstall

# Enable cloning from github
alias git_certs='watch -n 240 "ssh -T org-49461806@github.com;ssh-add -D;ssh-add -K"' 

alias gcloud_auth="gcloud auth login; gcloud auth application-default login; gcloud auth configure-docker"
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
 
# Adding libexec/bin to path
export PATH=$PATH:$HOMEBREW_PREFIX/opt/python/libexec/bin


# hermit in prompt
function prompt_hermit() {
  if [[ -n $HERMIT_ENV ]]; then
    p10k segment -t "${${HERMIT_ENV:t}//\%/%%} 🐚"  -f blue
  fi
}

# To customize prompt, run `p10k configure` or edit ~/Development/dotfiles/config/zsh/.p10k.zsh.
[[ ! -f ~/Development/dotfiles/config/zsh/.p10k.zsh ]] || source ~/Development/dotfiles/config/zsh/.p10k.zsh

# Generated by Hermit; START; DO NOT EDIT.
HERMIT_ROOT_BIN="${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.

eval "$(direnv hook zsh)"
export PIPX_DEFAULT_PYTHON=python3.10
 
# Adding libexec/bin to path
export PATH=$PATH:/opt/homebrew/opt/python@3/libexec/bin
# Adding libpq to path
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

p10k finalize
